.TH xlight 1
.SH NAME
xlight \- extremly lightweight and simple brightness control
.SH SYNOPSIS
.B xlight
[\fB\+-[0\-1234]\fR]
.SH DESCRIPTION
.B xlight
controls your brightness by directly modifying the brightness-file
.SH OPTIONS
.TP
.BR \+X
increases the value in the brightness-file by X.
If the value should drop below 0, it will be set to 0.
.TP
.BR \-X
decreases the value in the brightness-file by X.
If the value should be greater then the maximum, it is set to the maximum.
